namespace KubeMind.Brain.Application.Services;

/// <summary>
/// Defines a contract for checking if an incident has been seen recently.
/// </summary>
public interface IIncidentDeduplicationService
{
    /// <summary>
    /// Checks if a given incident is a duplicate within a configured time window.
    /// </summary>
    /// <param name="incidentId">A unique identifier for the incident, generated by the Observer.</param>
    /// <param name="cancellationToken">A cancellation token.</param>
    /// <returns>True if the incident is a duplicate, false otherwise.</returns>
    Task<bool> IsDuplicateAsync(string incidentId, CancellationToken cancellationToken = default);
}
