// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: incident.proto

package proto

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IncidentContext is the structured payload sent from the Observer to the Brain.
type IncidentContext struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	IncidentId             string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	PodName                string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace           string                 `protobuf:"bytes,3,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	FailureReason          string                 `protobuf:"bytes,4,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`                              // e.g., "OOMKilled", "CrashLoopBackOff"
	Logs                   string                 `protobuf:"bytes,5,opt,name=logs,proto3" json:"logs,omitempty"`                                                                     // Last N lines of logs
	PodManifestJson        string                 `protobuf:"bytes,6,opt,name=pod_manifest_json,json=podManifestJson,proto3" json:"pod_manifest_json,omitempty"`                      // Redacted Pod manifest
	DeploymentManifestJson string                 `protobuf:"bytes,7,opt,name=deployment_manifest_json,json=deploymentManifestJson,proto3" json:"deployment_manifest_json,omitempty"` // Redacted Deployment manifest
	Timestamp              *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *IncidentContext) Reset() {
	*x = IncidentContext{}
	mi := &file_incident_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncidentContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncidentContext) ProtoMessage() {}

func (x *IncidentContext) ProtoReflect() protoreflect.Message {
	mi := &file_incident_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncidentContext.ProtoReflect.Descriptor instead.
func (*IncidentContext) Descriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{0}
}

func (x *IncidentContext) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *IncidentContext) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *IncidentContext) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *IncidentContext) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *IncidentContext) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

func (x *IncidentContext) GetPodManifestJson() string {
	if x != nil {
		return x.PodManifestJson
	}
	return ""
}

func (x *IncidentContext) GetDeploymentManifestJson() string {
	if x != nil {
		return x.DeploymentManifestJson
	}
	return ""
}

func (x *IncidentContext) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// The response message for the StreamIncident RPC.
type StreamIncidentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamIncidentResponse) Reset() {
	*x = StreamIncidentResponse{}
	mi := &file_incident_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamIncidentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamIncidentResponse) ProtoMessage() {}

func (x *StreamIncidentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_incident_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamIncidentResponse.ProtoReflect.Descriptor instead.
func (*StreamIncidentResponse) Descriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{1}
}

func (x *StreamIncidentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_incident_proto protoreflect.FileDescriptor

const file_incident_proto_rawDesc = "" +
	"\n" +
	"\x0eincident.proto\x12\bkubemind\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x02\n" +
	"\x0fIncidentContext\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x03 \x01(\tR\fpodNamespace\x12%\n" +
	"\x0efailure_reason\x18\x04 \x01(\tR\rfailureReason\x12\x12\n" +
	"\x04logs\x18\x05 \x01(\tR\x04logs\x12*\n" +
	"\x11pod_manifest_json\x18\x06 \x01(\tR\x0fpodManifestJson\x128\n" +
	"\x18deployment_manifest_json\x18\a \x01(\tR\x16deploymentManifestJson\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"0\n" +
	"\x16StreamIncidentResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2b\n" +
	"\x0fIncidentService\x12O\n" +
	"\x0eStreamIncident\x12\x19.kubemind.IncidentContext\x1a .kubemind.StreamIncidentResponse(\x01B\"Z\x0fkube-mind/proto\xaa\x02\x0eKubeMind.Protob\x06proto3"

var (
	file_incident_proto_rawDescOnce sync.Once
	file_incident_proto_rawDescData []byte
)

func file_incident_proto_rawDescGZIP() []byte {
	file_incident_proto_rawDescOnce.Do(func() {
		file_incident_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_incident_proto_rawDesc), len(file_incident_proto_rawDesc)))
	})
	return file_incident_proto_rawDescData
}

var file_incident_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_incident_proto_goTypes = []any{
	(*IncidentContext)(nil),        // 0: kubemind.IncidentContext
	(*StreamIncidentResponse)(nil), // 1: kubemind.StreamIncidentResponse
	(*timestamp.Timestamp)(nil),    // 2: google.protobuf.Timestamp
}
var file_incident_proto_depIdxs = []int32{
	2, // 0: kubemind.IncidentContext.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: kubemind.IncidentService.StreamIncident:input_type -> kubemind.IncidentContext
	1, // 2: kubemind.IncidentService.StreamIncident:output_type -> kubemind.StreamIncidentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_incident_proto_init() }
func file_incident_proto_init() {
	if File_incident_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_incident_proto_rawDesc), len(file_incident_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_incident_proto_goTypes,
		DependencyIndexes: file_incident_proto_depIdxs,
		MessageInfos:      file_incident_proto_msgTypes,
	}.Build()
	File_incident_proto = out.File
	file_incident_proto_goTypes = nil
	file_incident_proto_depIdxs = nil
}
