// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: incident.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IncidentService_StreamIncident_FullMethodName = "/kubemind.IncidentService/StreamIncident"
)

// IncidentServiceClient is the client API for IncidentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The gRPC service for sending incidents.
type IncidentServiceClient interface {
	// A client-streaming RPC to send incident data.
	StreamIncident(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IncidentContext, StreamIncidentResponse], error)
}

type incidentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIncidentServiceClient(cc grpc.ClientConnInterface) IncidentServiceClient {
	return &incidentServiceClient{cc}
}

func (c *incidentServiceClient) StreamIncident(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IncidentContext, StreamIncidentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IncidentService_ServiceDesc.Streams[0], IncidentService_StreamIncident_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IncidentContext, StreamIncidentResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IncidentService_StreamIncidentClient = grpc.ClientStreamingClient[IncidentContext, StreamIncidentResponse]

// IncidentServiceServer is the server API for IncidentService service.
// All implementations must embed UnimplementedIncidentServiceServer
// for forward compatibility.
//
// The gRPC service for sending incidents.
type IncidentServiceServer interface {
	// A client-streaming RPC to send incident data.
	StreamIncident(grpc.ClientStreamingServer[IncidentContext, StreamIncidentResponse]) error
	mustEmbedUnimplementedIncidentServiceServer()
}

// UnimplementedIncidentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIncidentServiceServer struct{}

func (UnimplementedIncidentServiceServer) StreamIncident(grpc.ClientStreamingServer[IncidentContext, StreamIncidentResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamIncident not implemented")
}
func (UnimplementedIncidentServiceServer) mustEmbedUnimplementedIncidentServiceServer() {}
func (UnimplementedIncidentServiceServer) testEmbeddedByValue()                         {}

// UnsafeIncidentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IncidentServiceServer will
// result in compilation errors.
type UnsafeIncidentServiceServer interface {
	mustEmbedUnimplementedIncidentServiceServer()
}

func RegisterIncidentServiceServer(s grpc.ServiceRegistrar, srv IncidentServiceServer) {
	// If the following call panics, it indicates UnimplementedIncidentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IncidentService_ServiceDesc, srv)
}

func _IncidentService_StreamIncident_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IncidentServiceServer).StreamIncident(&grpc.GenericServerStream[IncidentContext, StreamIncidentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IncidentService_StreamIncidentServer = grpc.ClientStreamingServer[IncidentContext, StreamIncidentResponse]

// IncidentService_ServiceDesc is the grpc.ServiceDesc for IncidentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IncidentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kubemind.IncidentService",
	HandlerType: (*IncidentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamIncident",
			Handler:       _IncidentService_StreamIncident_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "incident.proto",
}
