namespace KubeMind.Brain.Application.Models;

/// <summary>
/// Represents a resolved incident to be stored in cognitive memory.
/// </summary>
/// <param name="IncidentId">The unique identifier of the incident.</param>
/// <param name="ClusterId">The cluster identifier.</param>
/// <param name="Namespace">The namespace of the affected pod.</param>
/// <param name="RawLog">The raw log content.</param>
/// <param name="Resolution">The resolution or diagnosis generated by the AI.</param>
public record IncidentResolution(
    Guid IncidentId,
    string ClusterId,
    string Namespace,
    string RawLog,
    string Resolution);
