using KubeMind.Brain.Application.Services;
using KubeMind.Brain.Infrastructure.Data;
using KubeMind.Proto;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.VectorData;
using System.Text;

namespace KubeMind.Brain.Infrastructure.Services;

/// <summary>
/// Provides services for enriching incident goals with historical context using cognitive memory.
/// </summary>
/// <remarks>
/// Initializes a new instance of the <see cref="EnrichmentService"/> class.
/// </remarks>
/// <param name="vectorStore">The vector store for searching historical incidents.</param>
/// <param name="embeddingGenerator">The service for generating text embeddings.</param>
/// <param name="logger">The logger instance.</param>
public class EnrichmentService(
    VectorStore vectorStore,
    IEmbeddingGenerator<string, Embedding<float>> embeddingGenerator,
    ILogger<EnrichmentService> logger) : IEnrichmentService
{

    /// <summary>
    /// Enriches the original goal with context from similar historical incidents found in the vector database.
    /// </summary>
    /// <param name="incident">The incident context containing logs and metadata.</param>
    /// <param name="originalGoal">The original goal generated by the planner.</param>
    /// <param name="ct">Cancellation token for the operation.</param>
    /// <returns>The enriched goal containing historical context, or the original goal if no relevant history is found.</returns>
    public async Task<string> EnrichGoalWithCognitiveMemoryAsync(
        IncidentContext incident,
        string originalGoal,
        CancellationToken ct = default)
    {
        try
        {
            var incidentLog = incident.Logs;
            
            if (string.IsNullOrWhiteSpace(incidentLog))
            {
                return originalGoal;
            }

            var embedding = await embeddingGenerator.GenerateAsync([incidentLog], cancellationToken: ct);
            var vector = embedding[0].Vector;

            var collection = vectorStore.GetCollection<Guid, IncidentMemory>("k8s_incidents");

            var searchOptions = new VectorSearchOptions<IncidentMemory>
            {
                VectorProperty = x => x.Embedding 
            };

            var searchResults = collection.SearchAsync(vector, 3, searchOptions, ct);

            var contextBuilder = new StringBuilder();
            
            await foreach (var result in searchResults)
            {
                var memory = result.Record; 
                contextBuilder.AppendLine($"[Similar Incident]: {memory.RawLog}");
                contextBuilder.AppendLine($"Resolution: {memory.ResolutionAction}");
                contextBuilder.AppendLine("---");
            }
            
            if (contextBuilder.Length > 0)
            {
                 return $"""
                    {originalGoal}

                    HISTORICAL CONTEXT FROM MEMORY:
                    {contextBuilder}
                    """;
            }

            return originalGoal;
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Failed to enrich goal with cognitive memory. Proceeding with original goal.");
            return originalGoal;
        }
    }
}
